// Auto-generated batch descriptions for catalog-data.js
// Run via: node tools/apply-descriptions.js (or paste into run_script)
// Each description follows v3 spec: 134-155 words, brand voice rules, LED specs per category.

window.__newDescriptions = {

  // ===================================================================
  // LED LAEPROFIILID — 10 SKUs (LED spec: 12 W/m · 234 LED/m · 3000K · 24V)
  // ===================================================================

  "LHV10-lae": "LHV10 lae-versioon on 10 mm laiusega peidetud LED varjuprofiil — sama mudel, mis põrandas, kuid sobiv ka lae ja seina ühenduskohta. Peen 10 mm varjujoon annab silmale alateadliku märguande lae-piirist, ilma et ükski detail tähelepanu tõmbaks. Sisseehitatud LED-kanal annab pehme peitevalgustuse perimeetri ulatuses; valgust ei ole näha LED-ribana, vaid ühtlase joone-valgusena lae serval. Sobib eriti hästi kõrgete lagedega ruumides, kus laiem profiil mõjuks raskelt. Pahteldatav servaga — paigaldatakse kipsplaadi alla nii, et profiili äär jääb plaadi tasapinnaga ühte; üleminek viimistlusjärgselt nähtamatu. Standardpikkus 2,5 m. Värvid: töötlemata, valge, must; RAL-tellimusel mistahes toon (~5 nädalat). Soovitatud LED-riba: 12 W/m, 234 LED/m, 3000K, 24V. Hind kehtib 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam.",

  "RST14": "RST14 on lae LED varjuprofiil 13 mm laiusega — paigaldatud lae ja seina ühenduskohta nii, et üks äär sulandub kipsplaadi tasapinnaga, teine jääb seinapinnaga ühte. Sees olev LED-kanal annab pehme valgusjoone toa perimeetri ulatuses. Profiil sobib hästi neutraalseks lae-detailiks, kui ei taheta liiga laia varjujoont — 13 mm jääb märgatavaks, kuid mitte domineerivaks. Värvuspaleti hulgas on ka anodeeritud hõbe, mis sobib hõbedaste pinnaviimistlustega ruumidesse. Pahteldatav servaga, kipsplaadi alla paigaldus. Standardpikkus 2,5 m, materjal alumiinium. Soovitatud LED-riba: 12 W/m, 234 LED/m, 3000K, 24V — kõrge LED-tihedus annab täiesti ühtlase valguse ilma nähtavate täppideta. LED-riba ja hajuti tellitakse eraldi. Hinnad on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam.",

  "AST35": "AST35 on 35 mm laiusega lae LED varjuprofiil — meie laiem standard-mudel, mis sobib avaramatesse ruumidesse, kõrgemate lagedega ruumidesse ja avalikesse ruumidesse, kus laiem varjujoon mõjub esindusliku detailina. Võrdluseks: AST22 on 22,5 mm, AST25 on 25 mm. Laiem süvend tähendab rohkem ruumi LED-ribale ja hajutile — valgus jaotub ühtlaselt ja silm ei näe LED-täppe profiili sees. Profiil annab korraga varjuefekti ja pehme peitevalgustuse perimeetri ulatuses. Paigaldatakse lae ja seina ühenduskohta, pahteldatav servaga; üleminek kipsplaadi tasapinnaga ühte. Standardpikkus 2,5 m. Värvid: töötlemata, valge, must; RAL-tellimusel mistahes toon (~5 nädalat). Soovitatud LED-riba: 12 W/m, 234 LED/m, 3000K, 24V. LED-riba ja hajuti tellitakse eraldi. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu.",

  "AST30": "AST30 on 30 mm laiusega lae LED varjuprofiil — vahe-mõõt AST25 (25 mm) ja AST35 (35 mm) vahel. Sobib siis, kui projekt nõuab silmatorkavamat varjujoont kui 25 mm, aga 35 mm tunduks juba liiga lai. Profiili sees on integreeritud LED-kanal, mis annab pehme peitevalgustuse perimeetri ulatuses. 30 mm süvend annab piisavalt ruumi LED-ribale + hajutile, et valgus jaotuks ühtlaselt ilma nähtavate täppideta. Paigaldatakse lae ja seina ühenduskohta — pahteldatav servaga, kipsplaadi tasapinnaga ühte. Sageli kasutatud elutubades ja koridorides, kus on soov tugevama varjujoone järele, kuid AST35 mõjuks raskelt. Standardpikkus 2,5 m. Värvid: töötlemata, valge, must; RAL-tellimusel mistahes toon. Soovitatud LED-riba: 12 W/m, 234 LED/m, 3000K, 24V. LED-riba ja hajuti tellitakse eraldi.",

  "AST14_12": "AST14_12 on 14 mm laiusega lae LED varjuprofiil — peene varjujoonega mudel sisseehitatud LED-kanaliga. Vahepealne valik nende vahel, kes peavad AST5 / AST8 / AST10 liiga peeneks ja AST22 / AST25 liiga laiaks. 14 mm joon jääb märgatavaks arhitektuurseks detailiks, kuid ei domineeri ruumis. Värvuspaleti hulgas on anodeeritud hõbe, mis sobib eriti hõbedaste või neutraalsete pinnaviimistlustega. Paigaldatakse lae ja seina ühenduskohta, pahteldatav servaga — üleminek kipsplaadi tasapinnaga viimistlusjärgselt nähtamatu. Standardpikkus 2,5 m, materjal alumiinium. Soovitatud LED-riba: 12 W/m, 234 LED/m, 3000K, 24V — kõrge tihedus annab ühtlase valguse. LED-riba ja hajuti tellitakse eraldi. Hinnad on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam, küsi pakkumist.",

  "RST25": "RST25 on 25 mm laiusega lae LED varjuprofiil — sama mõõt kui populaarsel AST25-l, kuid erineva geomeetriaga süvendiga. Alternatiiv neile, kes eelistavad RST-seeria profiili kuju ja paigaldusmeetodit. Sisseehitatud LED-kanal annab pehme peitevalgustuse perimeetri ulatuses; 25 mm laius annab piisavalt ruumi nii LED-ribale kui hajutile, mistõttu valgus jaotub ühtlaselt ilma nähtavate täppideta. Sobib elutubadesse, magamistubadesse ja suurematesse koridoridesse, kus laiem varjujoon mõjub esindusliku detailina. Paigaldatakse lae ja seina ühenduskohta — pahteldatav servaga, kipsplaadi tasapinnaga ühte. Standardpikkus 2,5 m, materjal alumiinium. Värvid: töötlemata, valge, must; RAL-tellimusel mistahes toon (~5 nädalat). Soovitatud LED-riba: 12 W/m, 234 LED/m, 3000K, 24V. LED-riba ja hajuti tellitakse eraldi. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu.",

  "AST218": "AST218 on lae LED varjuprofiil 22 mm laiusega — kompaktne mudel sisseehitatud LED-kanaliga, lähedane AST22 mõõdule, kuid pisut erineva sisemise geomeetriaga. Mõeldud nii uusehitistesse kui ka renoveerimisprojektidesse, kus on vaja kombineerida ühtlane varjujoon ja pehme peitevalgustus toa perimeetri ulatuses. Standardpikkus 2,5 m tähendab tüüpilise ruumi jaoks vähem jätkukohti, mis hoiab varjujoone visuaalselt katkematuna. Pahteldatav servaga — paigaldatakse kipsplaadi alla nii, et profiili äär jääb plaadi tasapinnaga ühte; üleminek pärast viimistlust nähtamatu. Värvid: töötlemata, valge, must; RAL-tellimusel mistahes toon (~5 nädalat). Soovitatud LED-riba: 12 W/m, 234 LED/m, 3000K, 24V. Hajuti tellitakse eraldi. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam, küsi pakkumist.",

  "AST12": "AST12 on 12 mm laiusega lae LED varjuprofiil — vahepealne mudel AST10 (10 mm, ilma LED-ita) ja AST14_12 (14 mm) vahel. Erinev AST10-st selle poolest, et AST12-s on sisseehitatud LED-kanal. 12 mm jääb visuaalselt peeneks, kuid annab silmale piisava arhitektuurse signaali. Sobib eriti hästi väiksematesse ruumidesse, kus laiem varjujoon mõjuks raskelt; ka kõrgematesse lagedega ruumidesse, kus profiil on vaadeldav distantsilt ja peenem joon töötab paremini. Sees olev LED annab pehme valgusvõnke toa perimeetri ulatuses. Paigaldatakse lae ja seina ühenduskohta, pahteldatav servaga — üleminek kipsplaadi tasapinnaga viimistlusjärgselt nähtamatu. Standardpikkus 2,5 m, materjal alumiinium. Värvid: töötlemata, valge, must; RAL-tellimusel mistahes toon. Soovitatud LED-riba: 12 W/m, 234 LED/m, 3000K, 24V. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu.",

  "RST22": "RST22 on 22 mm laiusega eraldav lae LED varjuprofiil — kasutatakse kahe pinna eraldamiseks (näiteks kahe lae-tasapinna vahel või lae ja seinapaneeli vahel). Erinevus tavalisest lae-seina varjuprofiilist on selles, et RST-seeria profiilid on mõeldud paigaldamiseks kahe kipsplaatide tasapinna vahele, mitte lae ja seina nurka. Sisseehitatud LED-kanal annab pehme valgusvõnke profiili joonel — sobib eriti hästi rühma- ja ruumi-piiride visuaalseks markeerimiseks, kus klassikaline seinaprofiil ei sobi. 22 mm laius annab korraga selge eraldatuse ja piisavalt ruumi LED-ribale. Standardpikkus 2,5 m, materjal alumiinium. Värvid: töötlemata, valge, must; RAL-tellimusel mistahes toon. Soovitatud LED-riba: 12 W/m, 234 LED/m, 3000K, 24V. LED-riba ja hajuti tellitakse eraldi. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu.",

  "RST40": "RST40 on 40 mm laiusega eraldav lae LED varjuprofiil meie valiku kõige laiem RST-seeria mudel ja kõige rohkem ruumi LED-le. Mõeldud kahe lae-pinna eraldamiseks või suurte lae-tasapindade visuaalseks segmenteerimiseks, kus on vaja silmatorkavat valgus-joont. 40 mm laius annab piisavalt ruumi nii LED-ribale kui ka korralikule hajutile — tulemus on tasane valgusjoon, kus LED-täppe ei ole näha isegi väikeselt distantsilt. Sobib eriti hästi suurtesse avalikesse ruumidesse, esindusruumidesse ja ärimaastikele, kus on vaja arhitektuurset valgust dramaatilise detailina. Erinev teistest RST-seeria profiilidest ka selle poolest, et standardpikkus on 3 m — vähem jätkukohti pikkadel sirgetel pindadel. Värvid: töötlemata, valge, must; RAL-tellimusel mistahes toon. Soovitatud LED-riba: 12 W/m, 234 LED/m, 3000K, 24V. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu.",

  // ===================================================================
  // LED PÕRAND + SEIN — 9 SKUs (LED: COB 16 W/m · 1350 lm/m · CRI 94 · 24V)
  // ===================================================================

  "LHV10-poranda": "LHV10 põranda-versioon on 10 mm laiusega peidetud paigaldusega LED varjuprofiil — paigaldatakse põranda ja seina ühenduskohta nii, et profiil asendab traditsioonilise põrandaliistu. Sees olev LED-kanal annab pehme valgusjoone põranda perimeetri ulatuses — efekt on selge: hõljuva seina mulje, pehme ööval ja vaoshoitud öövalgustus liikumistee jaoks ilma seinas oleva valgusti vajaduseta. 20 mm profiili kõrgus tähendab, et LED-kanal jääb nähtavale ainult valgust kiirgava joone-osaga; ülejäänud konstruktsioon sulandub seinatasandiga. Paigaldatakse seinapinnaga ühtsesse tasapinda — peidetud servaga, ilma nähtavate kinnitustega. Standardpikkus 2,5 m, materjal alumiinium. Värvid: töötlemata, valge, must; RAL-tellimusel mistahes toon. Soovitatud LED-riba: COB 16 W/m, 1350 lm/m, CRI 94, 24V — pidev valgusjoon ilma LED-täppideta. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu.",

  "ASPL60": "ASPL60 on 35 mm kõrgune põranda + seina LED varjuprofiil — universaalne mudel, mida saab paigaldada nii põranda ja seina ühendusele kui ka vertikaalselt seinapinda. Sisseehitatud LED-kanal annab pehme peidetud valguse — sobib ööval-stseenide jaoks, koridoride valgustuseks ilma seinavalgustite vajaduseta või dekoratiivse valguskonstruktsiooni jaoks suurtel pindadel. 35 mm kõrgus annab piisavalt ruumi nii COB LED-le kui hajutile. Värvuspaleti hulgas anodeeritud hõbe ja must, mis sobivad nii heledatesse kui tumedatesse interjööridesse. Paigaldatakse peidetud servaga — kipsplaadi alla, profiili äär jääb seinapinna tasandiga ühte. Standardpikkus 2,6 m, materjal alumiinium. Värvid: töötlemata, hõbe, must; RAL-tellimusel mistahes toon. Soovitatud LED-riba: COB 16 W/m, 1350 lm/m, CRI 94, 24V — pidev sileda kiirega valgusjoon. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu.",

  "ASPL35": "ASPL35 on 35 mm kõrgune põranda LED varjuprofiil — kompaktsem mudel ASPL100 ja ASPL60 kõrval. Sobib hästi tavalise eluruumi põrandaliistu asendamiseks, kus pole vaja silmatorkavat profiili-massi, kuid soovitakse pehmet peidetud valgust põranda joonel. Sisseehitatud LED-kanal annab valgust põranda perimeetri ulatuses — efekt on hõljuva seina mulje koos vaoshoitud ööval-stseeni võimalusega. Värvuspalett hõlmab töötlemata, anodeeritud hõbe, must ning RAL-tellimusel mistahes toon. Paigaldatakse peidetud paigaldusega — profiili äär jääb seinapinna tasandiga ühte, ilma nähtavate kinnitustega. Standardpikkus 2,6 m, materjal alumiinium. Soovitatud LED-riba: COB 16 W/m, 1350 lm/m, CRI 94, 24V — pidev valgusjoon ilma LED-täppideta. LED-riba ja hajuti tellitakse eraldi. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam.",

  "ASP905": "ASP905 on 49,5 mm kõrgune põranda LED varjuprofiil — keskmise kõrgusega mudel, mis on visuaalselt selgem kui kompaktsed 30 mm profiilid, kuid mitte nii dominantne kui ASPL100. Sobib hästi avaramatesse eluruumidesse ja arhitektuurset detaili otsivatesse projektidesse, kus põrandaliistu asemel soovitakse selget valguskonstruktsiooni. Sisseehitatud LED-kanal annab pehme peitevalgustuse põranda joonel — saab kasutada ka iseseisva öövalgustusena. Paigaldatakse peidetud servaga, kipsplaadi alla — üleminek seinapinnaga viimistlusjärgselt nähtamatu. Standardpikkus 2,6 m, materjal alumiinium. Värvid: töötlemata, must; RAL-tellimusel mistahes toon (~5 nädalat). Soovitatud LED-riba: COB 16 W/m, 1350 lm/m, CRI 94, 24V — pidev sileda kiirega valgusjoon, ilma LED-täppideta. LED-riba ja hajuti tellitakse eraldi. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu.",

  "ASP904": "ASP904 on 49,5 mm kõrgune põranda LED varjuprofiil — sama kõrgusega kui ASP905, kuid erineva sisemise geomeetriaga ja teistsuguse paigalduse-süvendiga. Alternatiiv neile, kelle ehituses on ASP905 paigaldus keeruline või kes eelistavad teistsugust profiili kuju. LED-kanal annab pehme valgusjoone põranda perimeetri ulatuses. Sobib eluruumidesse ja avalikesse ruumidesse, kus on vaja kombineerida traditsioonilise põrandaliistu funktsioon (seina alumise ääre kaitse) ja kaasaegne LED-valguslahendus. Paigaldatakse peidetud servaga — kipsplaadi alla, ilma nähtavate kinnitusteta. Standardpikkus 2,6 m, materjal alumiinium. Värvid: töötlemata, must; RAL-tellimusel mistahes toon. Soovitatud LED-riba: COB 16 W/m, 1350 lm/m, CRI 94, 24V — pidev valgusjoon ilma LED-täppideta. LED-riba ja hajuti tellitakse eraldi. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam.",

  "ASP410": "ASP410 on seina LED varjuprofiil 40 mm kõrgusega — alumiiniumprofiil sisseehitatud LED-kanaliga, paigaldatakse vertikaalselt seinapinda dekoratiivse valguse jaoks. Erinev tüüpilisest lae- või põrandaprofiilist selle poolest, et ASP410 on mõeldud seinasiseseks paigalduseks — saab kasutada näiteks ukse-piiride joonel, seina perimeetri ulatuses või dekoratiivse vertikaalse valgusjoone jaoks. 40 mm kõrgus annab piisavalt ruumi LED-ribale ja hajutile, et valgus jaotuks ühtlaselt; sobib eriti hästi kontoritesse, esindusruumidesse ja hotellide vestibüülidesse. Paigaldatakse pahteldatav servaga, kipsplaadi tasapinnaga ühte. Standardpikkus 2,6 m, materjal alumiinium. Värvus: töötlemata; RAL-tellimusel mistahes toon (~5 nädalat). Soovitatud LED-riba: COB 16 W/m, 1350 lm/m, CRI 94, 24V — pidev valgusjoon. LED-riba ja hajuti tellitakse eraldi. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu.",

  "ASP238": "ASP238 on 20 mm kõrgune põranda LED varjuprofiil — meie kompaktsem LED-iga mudel põranda jaoks. Hõlmab kõigi suuremate mudelite eelised (peidetud paigaldus, pehme valgusjoon, hõljuva seina mulje), kuid kompaktsemas vormis. Sobib eriti hästi väiksematesse eluruumidesse ja korteritesse, kus 35+ mm profiili kasutamine mõjuks raskelt. Värvuspalett hõlmab anodeeritud hõbe, must ja RAL-tellimusel mistahes toon. Paigaldatakse peidetud servaga, kipsplaadi alla — profiili äär jääb seinapinna tasandiga ühte, ilma nähtavate kinnitustega. Standardpikkus 2,6 m, materjal alumiinium. Soovitatud LED-riba: COB 16 W/m, 1350 lm/m, CRI 94, 24V — pidev valgusjoon ilma LED-täppideta. LED-riba ja hajuti tellitakse eraldi. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam, küsi pakkumist.",

  "ASPL130": "ASPL130 on 30 mm kõrgune põranda LED varjuprofiil — vahe-mudel ASPL35 (35 mm) ja kompaktsemate variantide vahel. Sobib hästi standardse eluruumi põrandaliistu asendamiseks, kui soovitakse pehmet peidetud valgust, kuid mitte dominantset profiili-konstruktsiooni. Sisseehitatud LED-kanal annab valgust põranda perimeetri ulatuses. Paigaldatakse peidetud servaga, kipsplaadi alla — üleminek seinapinnaga viimistlusjärgselt nähtamatu. Värvuspaleti hulgas must, mis sobib eriti hästi tumedate seintega ja kõrgekontrastsete interjööridega. Standardpikkus 2,6 m, materjal alumiinium. Värvid: töötlemata, must; RAL-tellimusel mistahes toon (~5 nädalat). Soovitatud LED-riba: COB 16 W/m, 1350 lm/m, CRI 94, 24V — pidev sileda kiirega valgusjoon, ilma LED-täppideta. LED-riba ja hajuti tellitakse eraldi. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam, küsi pakkumist.",

  "ASP106": "ASP106 on 60 mm kõrgune universaalne LED varjuprofiil — sobib nii põranda kui seina paigalduseks. Universaalsus tähendab, et sama tootenumbri saab tellida kõikidele kohtadele projektis, mis vähendab tarne-keerukust ja ühtlustab ruumi visuaalset väljanägemist. 60 mm kõrgus annab piisavalt ruumi LED-ribale ja korralikule hajutile — valgus jaotub ühtlaselt ilma nähtavate LED-täppideta. Sobib eriti hästi suuremate projektide jaoks, kus läbi mitme ruumi soovitakse sama profiili kasutada. Värvuspaleti hulgas anodeeritud hõbe, must ja RAL-tellimusel mistahes toon. Paigaldatakse peidetud servaga, kipsplaadi alla — profiili äär jääb pinnatasandiga ühte. Standardpikkus 2,6 m, materjal alumiinium. Soovitatud LED-riba: COB 16 W/m, 1350 lm/m, CRI 94, 24V — pidev valgusjoon. LED-riba ja hajuti tellitakse eraldi. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu.",

  "ASPL120": "ASPL120 on 30 mm kõrgune põranda LED varjuprofiil — alternatiiv ASPL130-le pisut erineva sisemise konstruktsiooniga ja teistsuguse paigaldus-süvendiga. Sobib hästi standardse eluruumi põrandaliistu asendamiseks, kus soovitakse vaoshoitud peidetud valgust ilma dominantse profiili-konstruktsioonita. Sisseehitatud LED-kanal annab pehme valgusjoone põranda perimeetri ulatuses — saab kasutada ka ainsa öövalgustusena pikemates koridorides. Paigaldatakse peidetud servaga, kipsplaadi alla — üleminek seinapinnaga viimistlusjärgselt nähtamatu. Standardpikkus 2,6 m, materjal alumiinium. Värvid: töötlemata, must; RAL-tellimusel mistahes toon (~5 nädalat). Soovitatud LED-riba: COB 16 W/m, 1350 lm/m, CRI 94, 24V — pidev sileda kiirega valgusjoon, ilma LED-täppideta. LED-riba ja hajuti tellitakse eraldi. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam, küsi pakkumist.",

  // ===================================================================
  // DEKORATIIVSED VARJUPROFIILID — 15 SKUs (ilma LED-ita)
  // ===================================================================

  "AST20": "AST20 on 10 mm peen lae varjuprofiil ilma LED-funktsioonita — sobib projektidesse, kus on vaja arhitektuurset varjujoont lae ja seina vahel, kuid mitte peitevalgustust. Tulemus on vaoshoitud joon, mida silm registreerib alateadlikult — ruum tundub viimistletum ilma, et üks detail tähelepanu tõmbaks. Sobib hästi väiksematesse ruumidesse, kus laiem profiil mõjuks raskelt, ning projektidesse, kus eelarves pole ruumi LED-süsteemi jaoks, kuid soovitakse siiski varjujoone-detaili. Pahteldatav servaga — paigaldatakse kipsplaadi alla nii, et profiili äär jääb plaadi tasapinnaga ühte; üleminek pärast viimistlust nähtamatu. Standardpikkus 2,5 m, materjal alumiinium. Värvid: töötlemata, valge, must; RAL-tellimusel mistahes toon (~5 nädalat). Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam, küsi pakkumist.",

  "AST10": "AST10 on 10 mm peen lae varjuprofiil ilma LED-funktsioonita — sama mõõt kui AST20-l, kuid teistsuguse sisemise profiili-kujuga ja pisut soodsama hinnaga. Alternatiiv neile, kelle ehituses on AST20 paigaldus keeruline või kes eelistavad pisut teistsugust süvendi-geomeetriat. Tulemus on vaoshoitud varjujoon lae ja seina ühenduskohas — ruum tundub viimistletum ilma silmatorkava detailita. Sobib eriti hästi väiksematesse ruumidesse ja korteritesse, kus laiem profiil mõjuks domineerivalt. Pahteldatav servaga — kipsplaadi alla, profiili äär jääb plaadi tasapinnaga ühte. Standardpikkus 2,5 m, materjal alumiinium. Värvid: töötlemata, valge, must; RAL-tellimusel mistahes toon (~5 nädalat). LED-funktsiooni ei ole — kui soovid lae LED-iga, vaata AST12 (sama-laiusega LED-versioon). Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu.",

  "AST8": "AST8 on 8 mm peen lae varjuprofiil — pärast AST5 (5 mm) meie teine kõige õhem mudel. Mõeldud projektidesse, kus on vaja võimalikult vaoshoitud varjujoont — selline, mida silm tajub alateadlikult, kuid mille olemasolu pole otseselt märgatav. Sobib hästi väiksematesse ruumidesse, magamistubadesse ja kabinettidesse, kus laiem profiil mõjuks raskelt. Tulemus on selge arhitektuurne detail — ilma silmatorkava elemendita. Pahteldatav servaga — paigaldatakse kipsplaadi alla nii, et profiili äär jääb plaadi tasapinnaga ühte; üleminek pärast viimistlust nähtamatu. Standardpikkus 2,5 m, materjal alumiinium. Värvid: töötlemata, valge, must; RAL-tellimusel mistahes toon (~5 nädalat). LED-funktsiooni ei ole — selle laiusega profiili sisse LED-riba ei mahu. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam.",

  "ASP611": "ASP611 on 60 mm kõrgune seina varjuprofiil — pahteldatav seina peiteprofiil, mida kasutatakse sissetõmmatud uksepiitade jaoks ja seina varjuks. Paigaldatakse vertikaalselt seinapinna ja ukseraami vahele nii, et tulemus on sile üleminek seinapinnaga, kus uks tundub justkui kasvavat seina sisest, ilma traditsioonilise ukseraami nähtava detailita. Sobib eriti hästi kaasaegsetesse interjööridesse, kus soovitakse minimalistlikku üleminekut uste ja seinte vahel. Pahteldatav servaga — kipsplaadi alla, profiili äär jääb plaadi tasapinnaga ühte; üleminek pärast viimistlust nähtamatu. Standardpikkus 2,6 m, materjal alumiinium. Värvus: töötlemata; RAL-tellimusel mistahes toon (~5 nädalat). Hind kehtib RAL-värvitud 1 m profiili kohta, sisaldab 24% käibemaksu; töötlemata profiili saab soodsamalt, küsi pakkumist.",

  "ASP411": "ASP411 on 40 mm kõrgune seina varjuprofiil — kompaktsem versioon ASP611-st (60 mm), mille kõrgus on vähendatud, et sobida väiksematesse ruumidesse ja kohtadesse, kus 60 mm mõjuks liiga laialt. Sama pahteldatava paigaldusega — sobib sissetõmmatud uksepiitadeks ja seinte vertikaalseks markeerimiseks. 40 mm tähendab, et profiili olemasolu tundub silmale arhitektuurse detailina, kuid ei domineeri. Sobib korteritesse, magamistubadesse ja koridoridesse, kus 60 mm profiili kasutamine oleks ülearu. Paigaldatakse kipsplaadi alla — profiili äär jääb plaadi tasapinnaga ühte; üleminek pärast viimistlust nähtamatu. Standardpikkus 2,6 m, materjal alumiinium. Värvus: töötlemata; RAL-tellimusel mistahes toon (~5 nädalat). Hind kehtib RAL-värvitud 1 m profiili kohta, sisaldab 24% käibemaksu; töötlemata profiili saab soodsamalt, küsi pakkumist.",

  "ASP198": "ASP198 on 91 mm kõrgune seina varjuprofiil — meie kõige kõrgem seina peiteprofiil. Mõeldud avalikesse ja esindusruumidesse, kus on vaja silmatorkavat seina-detaili: hotellide vestibüülidesse, kontoritesse, ärimaastikele. 91 mm laius tähendab, et profiil mõjub arhitektuurselt domineeriva detailina — sobib seinaplaatide vaheliste ühenduskohtade markeerimiseks, korruseülemineku visuaalseks rõhutamiseks, või suurte seinte segmenteerimiseks. Pahteldatav servaga — paigaldatakse kipsplaadi alla nii, et profiili äär jääb plaadi tasapinnaga ühte; üleminek pärast viimistlust nähtamatu. Standardpikkus 2,6 m, materjal alumiinium. Värvus: töötlemata; RAL-tellimusel mistahes toon (~5 nädalat). LED-funktsiooni ei ole. Hind kehtib RAL-värvitud 1 m profiili kohta, sisaldab 24% käibemaksu; töötlemata profiili saab soodsamalt, küsi pakkumist.",

  "ASP168": "ASP168 on 60 mm kõrgune seina varjuprofiil — sama kõrgusega kui ASP611, kuid teistsuguse sisemise profiili kujuga ja soodsamas hinnaklassis. Alternatiiv neile, kes ehituses eelistavad ASP168 paigaldusgeomeetriat või kelle eelarve ei luba ASP611-d. Kasutusala sama: pahteldatav seina peiteprofiil sissetõmmatud uksepiitadeks ja seinte vertikaalseks markeerimiseks. Tulemus on sile üleminek seinapinnaga — uks tundub justkui kasvavat seinasse. Pahteldatav servaga — paigaldatakse kipsplaadi alla, profiili äär jääb plaadi tasapinnaga ühte; üleminek pärast viimistlust nähtamatu. Standardpikkus 2,6 m, materjal alumiinium. Värvus: töötlemata; RAL-tellimusel mistahes toon (~5 nädalat). LED-funktsiooni ei ole. Hind kehtib RAL-värvitud 1 m profiili kohta, sisaldab 24% käibemaksu; töötlemata profiili saab soodsamalt, küsi pakkumist.",

  "ASP117": "ASP117 on 70 mm kõrgune põranda varjuprofiil — keskmise kõrgusega mudel ilma LED-funktsioonita. Sobib hästi traditsioonilise põrandaliistu asendamiseks, kus soovitakse selget arhitektuurset joont põranda ja seina vahel, kuid mitte peidetud valgustust. Värvuspaleti hulgas anodeeritud hõbe, mis sobib hõbedaste pinnaviimistlustega ruumidesse — kombinatsioon töötab eriti hästi kaasaegsete köökide ja vannitubadega. Paigaldatakse peidetud servaga, kipsplaadi alla — üleminek seinapinnaga viimistlusjärgselt nähtamatu. Standardpikkus 2,6 m, materjal alumiinium. Värvid: töötlemata, hõbe; RAL-tellimusel mistahes toon (~5 nädalat). LED-funktsiooni ei ole — kui soovid sama kõrgusega LED-versiooni, vaata ASP905 (49,5 mm, LED-iga). Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam, küsi pakkumist.",

  "ASP112": "ASP112 on 20 mm kõrgune põranda varjuprofiil — kompaktne mudel ilma LED-funktsioonita. Sobib hästi väiksematesse eluruumidesse ja korteritesse, kus soovitakse traditsioonilise põrandaliistu asendamist, kuid mitte ASPL35 või ASPL60 dominantset valgus-konstruktsiooni. Kompaktne kõrgus tähendab vaoshoitud joone-detaili põranda ja seina vahel — silm registreerib selle alateadlikult, ruum tundub viimistletum. Värvuspaleti hulgas anodeeritud hõbe ja must, mis sobivad nii heledatesse kui tumedatesse interjööridesse. Paigaldatakse peidetud servaga, kipsplaadi alla — üleminek seinapinnaga viimistlusjärgselt nähtamatu. Standardpikkus 2,6 m, materjal alumiinium. Värvid: töötlemata, hõbe, must; RAL-tellimusel mistahes toon (~5 nädalat). LED-funktsiooni ei ole — kui soovid sama kõrgusega LED-versiooni, vaata ASP238. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam.",

  "ASP115": "ASP115 on 53 mm kõrgune põranda varjuprofiil — keskmise kõrgusega mudel ilma LED-funktsioonita. Sobib projektidesse, kus on vaja selget põranda-seina üleminekut, kuid mitte LED-süsteemi keerukust ja maksumust. 53 mm annab joone, mis on silmale märgatav arhitektuurse detailina, ilma et profiil mõjuks domineerivalt. Paigaldatakse peidetud servaga, kipsplaadi alla — üleminek seinapinnaga viimistlusjärgselt nähtamatu, ilma nähtavate kinnitusteta. Standardpikkus 2,6 m, materjal alumiinium. Värvus: töötlemata; RAL-tellimusel mistahes toon (~5 nädalat). LED-funktsiooni ei ole — kui soovid LED-iga lähedast mõõtu, vaata ASP904 või ASP905 (49,5 mm, LED-iga). Hind kehtib RAL-värvitud 1 m profiili kohta, sisaldab 24% käibemaksu; töötlemata profiili saab soodsamalt, küsi pakkumist.",

  "ASP108": "ASP108 on 80 mm kõrgune põranda varjuprofiil — meie kõrgem dekoratiivne põrandaprofiil ilma LED-funktsioonita. 80 mm tähendab, et profiil mõjub esindusliku detailina — sobib eriti hästi suurematesse eluruumidesse, esindusruumidesse, ka töökorraldatud avalikkesse ruumidesse, kus traditsiooniline põrandaliist mõjuks tehniliselt ja kus soovitakse arhitektuurset üleminekut põranda ja seina vahel. Värvuspaleti hulgas anodeeritud hõbe, mis sobib hõbedaste pinnaviimistlustega ruumidesse. Paigaldatakse peidetud servaga, kipsplaadi alla — üleminek seinapinnaga viimistlusjärgselt nähtamatu. Standardpikkus 2,6 m, materjal alumiinium. Värvid: töötlemata, hõbe; RAL-tellimusel mistahes toon (~5 nädalat). LED-funktsiooni ei ole — kui soovid sama kõrgusega LED-versiooni, vaata ASPL100 (100 mm, LED-iga). Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam.",

  "AVP609": "AVP609 on 60 mm kõrgune ristkülikukujuline põrandaprofiil — alternatiiv tüüpilisele peidetud paigaldusega varjuprofiilile. Ristkülikukujuline geomeetria tähendab, et profiil ei sulandu seinapinnaga, vaid jääb pärast paigaldust silmaga märgatavaks ristkülik-konstruktsiooniks põranda joonel. Sobib projektidesse, kus on vaja selget ja tehniliselt loetavat üleminekut põranda ja seina vahel — näiteks ärimaastikele, kontorite koridoridesse, või eluruumidesse, kus soovitakse industriaalsemat aesthetic'ut. Värvuspaleti hulgas anodeeritud hõbe, mis sobib eriti hästi tehnilise või minimalistliku interjööri jaoks. Standardpikkus 2,6 m, materjal alumiinium. Värvid: töötlemata, hõbe; RAL-tellimusel mistahes toon (~5 nädalat). LED-funktsiooni ei ole. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam, küsi pakkumist.",

  "AVP859": "AVP859 on 85 mm kõrgune ristkülikukujuline põrandaprofiil — kõrgem versioon AVP609-st. Sama ristkülikukujuline geomeetria — profiil jääb pärast paigaldust silmaga märgatavaks ristkülik-konstruktsiooniks põranda joonel, mitte sileda peidetud üleminekuna. Kõrgem mõõt (85 mm) tähendab tugevamat visuaalset signaali — sobib eriti hästi suurematesse projektidesse, esindusruumidesse, kontorite vestibüülidesse, kus tehniliselt loetav põrandaliist on disainikohane otsus. Värvuspaleti hulgas anodeeritud hõbe, mis sobib industriaalsema ja minimalistliku interjööri jaoks. Standardpikkus 2,6 m, materjal alumiinium. Värvid: töötlemata, hõbe; RAL-tellimusel mistahes toon (~5 nädalat). LED-funktsiooni ei ole. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam, küsi pakkumist.",

  "AST101": "AST101 on lae varjuprofiil ilma LED-funktsioonita — sobib projektidesse, kus on vaja selget varjujoont lae ja seina vahel, kuid mitte peidetud valgustust. Tulemus on arhitektuurne detail — vaoshoitud joon, mis annab silmale alateadliku signaali lae-piirist, ilma et üks element tähelepanu tõmbaks. Sobib eluruumidesse ja korteritesse, kus eelarves pole ruumi LED-süsteemi jaoks või kus elektrijuhtmestiku paigaldus oleks renoveerimisel keeruline. Pahteldatav servaga — paigaldatakse kipsplaadi alla nii, et profiili äär jääb plaadi tasapinnaga ühte; üleminek pärast viimistlust nähtamatu. Standardpikkus 2,5 m, materjal alumiinium. Värvid: töötlemata, valge, must; RAL-tellimusel mistahes toon (~5 nädalat). LED-funktsiooni ei ole. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam, küsi pakkumist.",

  "RST1020": "RST1020 on eraldav lae varjuprofiil ilma LED-funktsioonita — sobib kasutamiseks kahe lae-pinna eraldamiseks või lae- ja seinapaneeli vahelise siirde markeerimiseks. RST-seeria profiilid on mõeldud paigaldamiseks kahe kipsplaatide tasapinna vahele, mitte lae ja seina nurka. Ilma LED-süsteemi keerukuse ja maksumuseta — sobib projektidesse, kus on vaja selget pinna-eraldatust, kuid mitte valguskonstruktsiooni. Sobib eriti hästi suuremate ruumide segmenteerimiseks ja lae-pindade akustilise või visuaalse jaotamiseks. Paigaldatakse pahteldatav servaga kahe pinna vahele — üleminek pärast viimistlust nähtamatu. Standardpikkus 2,5 m, materjal alumiinium. Värvid: töötlemata, valge, must; RAL-tellimusel mistahes toon (~5 nädalat). LED-funktsiooni ei ole — kui soovid sama-seeria LED-versiooni, vaata RST22 või RST40. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu.",

  // ===================================================================
  // ALUMIINIUM PÕRANDALIISTUD — 15 SKUs
  // ===================================================================

  "ASP58": "ASP58 on 58 mm kõrgune alumiinium põrandaliist Arrow-seeriast — kompaktsem versioon ASP78-st, sama nähtava paigaldusega põranda-detailina (mitte peidetud varjuprofiilina). Asetseb põranda peal ja seina kõrval, kuid moodne alumiinium-kuju erineb traditsioonilisest puidust või MDF-liistust — ei tõmba silma välja, vaid sobib visuaalselt nii kaasaegsete kui ka klassikaliste interjööride hulka. Värvuspaleti hulgas anodeeritud hõbe — sobib hästi kaasaegsete köökide ja vannitubadega. Lihtne paigaldus klipsidega; ei nõua erilist ehitusoskust ega kipsplaadi-süvendit. Standardpikkus 2,6 m, materjal alumiinium. Värvid: töötlemata, hõbe, valge, must; RAL-tellimusel mistahes toon (~5 nädalat). LED-funktsiooni ei ole. Hind on 1 m värvitud liistu kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam, küsi pakkumist.",

  "ASP36": "ASP36 on 36 mm kõrgune alumiinium põrandaliist — kompaktne nähtava paigaldusega liist. Hea sobivus väiksematesse eluruumidesse ja korteritesse, kus suuremad ASP58/ASP78 liistud mõjuksid raskelt, kuid soovitakse siiski alumiiniumist kaasaegset detaili traditsioonilise puidust liistu asemel. Lihtne paigaldus klipsidega; sobib uutele ja renoveeritavatele põrandatele. Värvuspalett (hõbe, valge, must) annab paindlikkust nii heledatesse kui tumedatesse interjööridesse. RAL-tellimusel saadaval mistahes toon. Erinevus varjuprofiilidest (ASP905, ASPL35 jne): ASP36 on traditsioonilisem nähtav liist, mitte peidetud paigaldusega — sobib siis, kui ehitusprojekt ei taha kipsplaadi-süvendit või kui renoveerimisel ei saa seinapinda muuta. Standardpikkus 2,5 m, materjal alumiinium. LED-funktsiooni ei ole. Hind on 1 m värvitud liistu kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam.",

  "MPA217": "MPA217 on 22 mm kõrgune alumiinium põrandaliist — kõige kompaktsem MPA-seeria liist meie valikus. Sobib eriti hästi väiksematesse ruumidesse, kus laiem põrandaliist mõjuks raskelt — väikesed magamistoad, garderoobid, vannituppade WC-osad. Vaoshoitud kõrgus annab silmale alateadliku põranda-seina ülemineku, ilma et liist tähelepanu tõmbaks. Lihtne paigaldus klipsidega — sobib uutele ja renoveeritavatele põrandatele. Värvuspalett (hõbe, valge, must) annab paindlikkust erinevatesse interjööridesse. RAL-tellimusel saadaval mistahes toon. Standardpikkus 2,6 m, materjal alumiinium. LED-funktsiooni ei ole. Erinevus tavalisest puidust või MDF-liistust: alumiinium ei imenda niiskust, ei pundu, ei muuda värvi ajaga — eluiga aastakümneid. Hind on 1 m värvitud liistu kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam, küsi pakkumist.",

  "MPA015": "MPA015 on 6,6 mm kõrgune alumiinium põrandaliist — meie kõige õhem MPA-seeria mudel. Pea peatselt nähtamatu — annab silmale ainult alateadliku põranda-seina ülemineku, ilma et liist mõjuks dekoratiivse detailina. Sobib eriti hästi minimalistlikesse interjööridesse, galerii- ja näituseruumidesse, või projektidesse, kus on vaja võimalikult vaoshoitud üleminekut põranda ja seina vahel. Lihtne paigaldus klipsidega — sobib uutele ja renoveeritavatele põrandatele. Värvuspalett (hõbe, valge, must) annab paindlikkust nii heledatesse kui tumedatesse interjööridesse. RAL-tellimusel saadaval mistahes toon. Standardpikkus 2,6 m, materjal alumiinium. LED-funktsiooni ei ole — 6,6 mm sees ei mahu LED-riba. Erinevus varjuprofiilidest: MPA015 on nähtava paigaldusega, ei vaja kipsplaadi-süvendit. Hind on 1 m värvitud liistu kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam.",

  "ASP100": "ASP100 on 100 mm kõrgune alumiinium põrandaliist — meie kõrgem Arrow-seeria liist nähtava paigaldusega. Sobib esindusruumidesse, suurematesse eluruumidesse ja avalikesse ruumidesse, kus kõrgem liist mõjub esindusliku detailina. 100 mm kõrgus annab tugeva visuaalse signaali põranda-seina üleminekul — sobib eriti hästi kõrgematele lagedele ja suurematele ruumidele, kus väiksem liist (ASP36, MPA217) mõjuks ebaproportsionaalsena. Lihtne paigaldus klipsidega; ei nõua kipsplaadi-süvendit. Otsakomplekt F100 (eraldi tellimisel) annab puhta lõpetuse sisenurkadele, välisnurkadele ja otsapeadele. Värvuspaleti hulgas anodeeritud hõbe, valge, must ja RAL-tellimusel mistahes toon (~5 nädalat). Standardpikkus 2,5 m, materjal alumiinium. LED-funktsiooni ei ole. Hind on 1 m värvitud liistu kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam.",

  "ASP80": "ASP80 on 80 mm kõrgune alumiinium põrandaliist Arrow-seeriast — keskmise kõrgusega liist nähtava paigaldusega. Sobib suurematesse eluruumidesse, kus väiksemad liistud (ASP36, ASP58) mõjuksid liiga väikseina, kuid 100 mm tunduks juba liiga dominantne. 80 mm kõrgus annab selge visuaalse signaali põranda-seina üleminekul, ilma et liist mõjuks ebaproportsionaalselt. Lihtne paigaldus klipsidega; otsakomplekt F80 (eraldi tellimisel) annab puhta lõpetuse sisenurkadele, välisnurkadele ja otsapeadele. Värvuspaleti hulgas anodeeritud hõbe, valge, must ja RAL-tellimusel mistahes toon (~5 nädalat). Standardpikkus 2,6 m, materjal alumiinium. LED-funktsiooni ei ole — kui soovid LED-iga lähedast kõrgust, vaata ASP106 (60 mm, LED-iga). Hind on 1 m värvitud liistu kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam.",

  "ASP60": "ASP60 on 60 mm kõrgune alumiinium põrandaliist Arrow-seeriast — populaarne keskmise kõrgusega mudel nähtava paigaldusega. Sobib hästi standardse eluruumi põrandaliistuks, kus on vaja kaasaegset alumiinium-detaili traditsioonilise puidust või MDF-liistu asemel. 60 mm jääb märgatavaks arhitektuurseks detailiks, kuid ei domineeri ruumis. Lihtne paigaldus klipsidega; otsakomplekt F60 (eraldi tellimisel) annab puhta lõpetuse sisenurkadele, välisnurkadele ja otsapeadele. Värvuspaleti hulgas anodeeritud hõbe, valge, must ja RAL-tellimusel mistahes toon (~5 nädalat). Standardpikkus 2,6 m, materjal alumiinium. LED-funktsiooni ei ole — kui soovid LED-iga sama kõrgusega versiooni, vaata ASP106. Hind on 1 m värvitud liistu kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam, küsi pakkumist.",

  "ASP40": "ASP40 on 40 mm kõrgune alumiinium põrandaliist Arrow-seeriast — kompaktsem nähtava paigaldusega liist anodeeritud kattekihiga. Anodeeritud pind annab liistule kõrgema pinnatugevuse ja vastupidavuse kriimustustele kui tavaline värvitud kate — eluiga aastakümneid. Sobib hästi kaasaegsetesse köökidesse, vannitubadesse ja koridoridesse, kus liist peab vastu pidevale puhastamisele ja kontaktile. 40 mm kõrgus on vaoshoitud — sobib väiksematesse ja keskmistesse eluruumidesse. Lihtne paigaldus klipsidega; otsakomplekt F40 (eraldi tellimisel) annab puhta lõpetuse sisenurkadele, välisnurkadele ja otsapeadele. Värvuspaleti hulgas anodeeritud hõbe, valge, must ja RAL-tellimusel mistahes toon (~5 nädalat). Standardpikkus 2,5 m, materjal alumiinium. LED-funktsiooni ei ole. Hind on 1 m värvitud liistu kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam.",

  "ASP38": "ASP38 on 38 mm kõrgune alumiinium põrandaliist — kompaktne nähtava paigaldusega mudel ASP36 ja ASP40 vahepealse kõrgusega. Sobib projektidesse, kus 36 mm jääks liiga peeneks ja 40 mm tunduks juba liiga lai. Pisut kõrgem kui ASP36 — annab silmale selge põranda-seina ülemineku, kuid ei mõju siiski domineerivalt. Lihtne paigaldus klipsidega — sobib uutele ja renoveeritavatele põrandatele. Värvuspalett (hõbe, valge, must) annab paindlikkust nii heledatesse kui tumedatesse interjööridesse. RAL-tellimusel saadaval mistahes toon (~5 nädalat). Standardpikkus 2,6 m, materjal alumiinium. LED-funktsiooni ei ole. Erinevus traditsioonilisest puidust või MDF-liistust: alumiinium ei imenda niiskust, ei pundu, ei muuda värvi ajaga. Hind on 1 m värvitud liistu kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam, küsi pakkumist.",

  "MPA013": "MPA013 on 19,2 mm kõrgune alumiinium põrandaliist TINLINE-seeriast — peen ja vaoshoitud mudel. Nähtav kõrgus on vaid 13 mm (ülejäänud 6 mm jääb põranda alla), profiili laius 16 mm. Sobib eriti hästi minimalistlikesse interjööridesse, kus on vaja vaoshoitud põranda-seina üleminekut. Erinevus tavalisest klips-kinnitusega liistust: MPA013 kinnitatakse vedru-süsteemiga (vedru iga 50 cm tagant; tellitakse eraldi, 0,50 € / tk + KM) — annab tugeva ja müravaba kinnituse, võimaldab vajadusel liistu eemaldada. Standardpikkus 2,6 m, materjal alumiinium. Värvid: hõbe, valge, must; RAL-tellimusel mistahes toon (~5 nädalat). LED-funktsiooni ei ole — kui soovid LED-iga TINLINE-i, vaata MPA302 või MPV301. Hind on 1 m värvitud liistu kohta, sisaldab 24% käibemaksu.",

  "MPA317": "MPA317 on alumiinium põrandaliist TINLINE-seeriast — peen ja vaoshoitud nähtava paigaldusega liist. Sarnaselt teistele TINLINE-mudelitele kinnitatakse vedru-süsteemiga — sobib uutele ja renoveeritavatele põrandatele. Värvuspalett (hõbe, valge, must) annab paindlikkust nii heledatesse kui tumedatesse interjööridesse. RAL-tellimusel saadaval mistahes toon (~5 nädalat). Sobib eriti hästi minimalistlikesse interjööridesse ja kaasaegsetesse korterite remontidesse, kus on vaja vaoshoitud põranda-seina üleminekut. Standardpikkus 2,6 m, materjal alumiinium. LED-funktsiooni ei ole — kui soovid LED-iga TINLINE-i, vaata MPA302 või MPV301. Hind on 1 m värvitud liistu kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam, küsi pakkumist. NB! Kontrolli laoseisu enne tellimist — MPA317 on harvem tellitav variant, võib olla kohale-saatmisega 2–3 nädalat.",

  "MPA302": "MPA302 on 31,2 mm kõrgune alumiinium põrandaliist TINLINE-seeriast LED-kanaliga — annab pehme peidetud valgusjoone põranda joonel ja korraga moodsa kaasaegse liistu funktsiooni. Nähtav kõrgus on 25 mm (ülejäänud 6 mm jääb põranda alla), profiili laius 16 mm. Sisseehitatud LED-kanal sobib pikkadeks koridoride valgustuseks, eluruumide ööval-stseenide jaoks ja dekoratiivseks põranda-detaiks. Valgusdifuusor tellitakse eraldi (2,50 € / m + KM); LED-riba ja toiteplokid samuti eraldi. Kinnitus vedru-süsteemiga (vedru iga 50 cm tagant; 0,50 € / tk + KM). Standardpikkus 2,6 m, materjal alumiinium. Värvid: hõbe, valge, must; RAL-tellimusel mistahes toon (~5 nädalat). Soovitatud LED-riba: COB 16 W/m, 1350 lm/m, CRI 94, 24V. Hind on 1 m värvitud liistu kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam.",

  "MVP018": "MVP018 on 9 mm kõrgune alumiinium põrandaliist — ülikõrge ja peen mudel sein-paigalduseks. Mõeldud projektidesse, kus on vaja võimalikult vaoshoitud üleminekut põranda ja seina vahel — selline, mida silm tajub ainult alateadlikult, kuid mille olemasolu ei mõju dekoratiivse detailina. Sobib eriti hästi galerii- ja näituseruumidesse, minimalistlikesse korterite remontidesse, ja projektidesse, kus tahetakse kombineerida alumiiniumi vastupidavus traditsiooniliselt nähtamatu liistu visuaaliga. Kinnitus vedru-süsteemiga (vedru iga 50 cm tagant; eraldi tellimisel). Värvuspalett (hõbe, valge, must) annab paindlikkust erinevatesse interjööridesse. RAL-tellimusel saadaval mistahes toon (~5 nädalat). Standardpikkus 2,6 m, materjal alumiinium. LED-funktsiooni ei ole — 9 mm sees ei mahu LED-riba. Hind on 1 m värvitud liistu kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam, küsi pakkumist.",

  "MVP172": "MVP172 on 22 mm kõrgune alumiinium põrandaliist — sein-paigalduseks mõeldud TINLINE-seeria liist. Vaoshoitud kõrgus annab silmale alateadliku põranda-seina ülemineku, ilma et liist mõjuks dekoratiivse detailina. Sobib eriti hästi väiksematesse ja keskmistesse eluruumidesse, ka avalikesse ruumidesse, kus 60 mm või suuremad liistud mõjuksid liiga raskelt. Kinnitus vedru-süsteemiga (vedru iga 50 cm tagant; eraldi tellimisel). Värvuspalett (hõbe, valge, must) annab paindlikkust erinevatesse interjööridesse. RAL-tellimusel saadaval mistahes toon (~5 nädalat). Standardpikkus 2,6 m, materjal alumiinium. LED-funktsiooni ei ole — kui soovid LED-iga sama-seeria mudelit, vaata MPV301. Erinevus traditsioonilisest puidust või MDF-liistust: alumiinium ei imenda niiskust, ei pundu, ei muuda värvi ajaga. Hind on 1 m värvitud liistu kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam.",

  "MPV301": "MPV301 on alumiinium põrandaliist TINLINE-seeriast LED-kanaliga — annab pehme peidetud valgusjoone põranda joonel. Sarnaselt MPA302-le on see osa TINLINE-mudelivalikust, mis ühildab moodsa kaasaegse põrandaliistu funktsiooni LED-süsteemiga. Sobib eluruumide ööval-stseenide jaoks, koridoride pehmeks valgustuseks ja dekoratiivseks põranda-detailiks. LED-riba, valgusdifuusor ja toiteplokid tellitakse eraldi. Kinnitus vedru-süsteemiga, mis annab tugeva ja müravaba kinnituse uutele ja renoveeritavatele põrandatele. Standardpikkus 2,6 m, materjal alumiinium. Värvid: hõbe, valge, must; RAL-tellimusel mistahes toon (~5 nädalat). Soovitatud LED-riba: COB 16 W/m, 1350 lm/m, CRI 94, 24V — pidev sileda kiirega valgusjoon, ilma LED-täppideta. Hind on 1 m värvitud liistu kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam, küsi pakkumist.",

  // ===================================================================
  // NURGAPROFIILID — 3 SKUs
  // ===================================================================

  "DKP1010": "DKP1010 on 10×10 mm alumiinium nurgaprofiil — dekoratiivne kaitseprofiil seinte välisnurkade jaoks. Paigaldatakse seinte välisnurka, kaitseb nurka kriimustuste ja löökide eest ning annab korraga puhta arhitektuurse joone. Sobib eriti hästi kohtadesse, kus läheb läbi palju liiklust — koridorid, ärimaastikud, hotellid, garderoobid — või kus seina nurgad on tundlikud kahjustustele (kipsplaat, värvitud krohvitud sein). 10×10 mm geomeetria on kompaktne — sobib siis, kui suurem profiil mõjuks raskelt. Värvuspalett (valge, must) annab paindlikkust erinevatesse interjööridesse. RAL-tellimusel saadaval mistahes toon (~5 nädalat). Standardpikkus 3 m, materjal alumiinium. Liimitakse või kruvitakse seina külge — kinnitusvahendid tellitakse eraldi. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam.",

  "DKP1515": "DKP1515 on 15×15 mm alumiinium nurgaprofiil — keskmise mõõduga dekoratiivne kaitseprofiil seinte välisnurkade jaoks. 15×15 mm tähendab, et profiil annab tugevama visuaalse signaali kui DKP1010 (10×10 mm), kuid ei mõju veel domineerivalt. Sobib eriti hästi keskmistesse eluruumidesse ja koridoridesse, kus on vaja kaitsta seinanurka kahjustuste eest ning korraga lisada arhitektuurset detaili. Värvuspalett (valge, must) annab paindlikkust erinevatesse interjööridesse. RAL-tellimusel saadaval mistahes toon (~5 nädalat). Standardpikkus 3 m, materjal alumiinium. Liimitakse või kruvitakse seina külge — kinnitusvahendid tellitakse eraldi. Sobib nii uutele kui ka renoveeritavatele projektidele. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam, küsi pakkumist.",

  "DKP2020": "DKP2020 on 20×20 mm alumiinium nurgaprofiil — meie suurim DKP-seeria mudel. 20×20 mm tähendab silmatorkavat arhitektuurset detaili seinanurka — sobib projektidesse, kus on vaja korraga selget visuaalset signaali ja tugevat kaitset seinanurga kahjustustele. Sobib hästi avalikesse ruumidesse (hotellid, ärimaastikud, kontorid, vestibüülid), kus seinte nurgad on pidevalt kontaktis liikujatega ja kus suurem profiil mõjub osana esindusliku interjööri disainist. Värvuspalett (valge, must) annab paindlikkust erinevatesse interjööridesse. RAL-tellimusel saadaval mistahes toon (~5 nädalat). Standardpikkus 3 m, materjal alumiinium. Liimitakse või kruvitakse seina külge — kinnitusvahendid tellitakse eraldi. Hind on 1 m värvitud profiili kohta, sisaldab 24% käibemaksu; töötlemata pind on soodsam, küsi pakkumist.",

  // ===================================================================
  // LISATARVIKUD — 11 SKUs
  // ===================================================================

  "ASL302": "ASL302 on LED-profiili valgusdifuusor (hajuti) — painduv lääts, mis paigaldatakse profiili LED-kanali kohale, et valgust hajutada. Hajutamata LED-riba näeb välja nähtavate täppidena, hajutiga aga tasase valgusjoonena. Sobib ASP-410 ja ASP-610 profiilidele. Polükarbonaatist (poolläbipaistev valge), silikoonist tihendiga — paigaldatakse profiili sisse libistamisega, ilma liimimata. Painduv: võimaldab paigaldust ka kõverustel. Hind on 1 m hajuti kohta, sisaldab 24% käibemaksu. NB! Hajutit on vaja iga LED-iga profiili jaoks, kui soovitakse pidevat valgusjoont — ilma hajutita on LED-riba küll funktsionaalne, kuid valgus jääb tehniline (täpid nähtavad). Tellitakse vastavalt LED-iga profiili kogusele. Tutvu ka ASL312 (ASPL-130 ja AST-14_12 jaoks) ning ASL300 (ASPL-seeria jaoks).",

  "ASL312": "ASL312 on LED-profiili valgusdifuusor (hajuti) — painduv lääts, mis paigaldatakse profiili LED-kanali kohale, et valgust hajutada. Hajutamata LED-riba näeb välja nähtavate täppidena, hajutiga aga tasase valgusjoonena. Sobib ASPL-130, RST-13/12 ja AST-14/12 profiilidele. Polükarbonaatist (poolläbipaistev valge), silikoonist tihendiga — paigaldatakse profiili sisse libistamisega, ilma liimimata. Painduv: võimaldab paigaldust ka kõverustel. Hind on 1 m hajuti kohta, sisaldab 24% käibemaksu. NB! Hajutit on vaja iga LED-iga profiili jaoks, kui soovitakse pidevat valgusjoont — ilma hajutita on LED-riba küll funktsionaalne, kuid valgus jääb tehniline (täpid nähtavad). Tellitakse vastavalt LED-iga profiili kogusele. Tutvu ka ASL302 (ASP-410/610 jaoks) ning ASL300 (ASPL-35/60/100 jaoks).",

  "ASL300": "ASL300 on LED-profiili valgusdifuusor (hajuti) — painduv lääts, mis paigaldatakse profiili LED-kanali kohale, et valgust hajutada. Hajutamata LED-riba näeb välja nähtavate täppidena, hajutiga aga tasase valgusjoonena. Sobib ASPL-35, ASPL-60 ja ASPL-100 profiilidele — kõige sagedamini tellitav hajuti meie valikust, kuna ASPL-seeria on populaarseim põranda LED-profiil. Polükarbonaatist (poolläbipaistev valge), silikoonist tihendiga — paigaldatakse profiili sisse libistamisega, ilma liimimata. Painduv: võimaldab paigaldust ka kõverustel. Hind on 1 m hajuti kohta, sisaldab 24% käibemaksu. NB! Hajutit on vaja iga LED-iga profiili jaoks, kui soovitakse pidevat valgusjoont — ilma hajutita on valgus tehniline (täpid nähtavad). Tellitakse vastavalt LED-iga profiili kogusele.",

  "ASL25": "ASL25 on LED-profiili valgusdifuusor (hajuti) — painduv lääts, mis paigaldatakse RST-25 profiili LED-kanali kohale. Hajutamata LED-riba näeb välja nähtavate täppidena, hajutiga aga tasase valgusjoonena. Polükarbonaatist (poolläbipaistev valge) — paigaldatakse profiili sisse libistamisega, ilma liimimata. Tarnitakse 3 m standardpikkuses, mis sobib RST-25 profiili tüüpilise pikkusega. Painduv: võimaldab paigaldust ka kõverustel. Hind on 3 m hajuti kohta (mitte 1 m), sisaldab 24% käibemaksu. NB! Hajutit on vaja iga LED-iga profiili jaoks, kui soovitakse pidevat valgusjoont — ilma hajutita on valgus tehniline. RST-25 ja ASL25 koos annab ühtlase varjujoone ja LED-valgusjoone kombinatsiooni, mis on RST-seeria peamine eelis tavaliste LED-profiilide ees.",

  "ASL40": "ASL40 on LED-profiili valgusdifuusor (hajuti) — painduv lääts, mis paigaldatakse AST-35 ja RST-40 profiilide LED-kanali kohale. Suuremate profiilide jaoks mõeldud — laiem läätse-kuju annab korraliku valguse hajutuse ka laiematel profiilidel, kus tavaline kitsam hajuti (ASL300, ASL302) ei kataks LED-riba täielikult. Polükarbonaatist (poolläbipaistev valge) — paigaldatakse profiili sisse libistamisega, ilma liimimata. Tarnitakse 3 m standardpikkuses. Painduv: võimaldab paigaldust ka kõverustel. Hind on 3 m hajuti kohta (mitte 1 m), sisaldab 24% käibemaksu. NB! Hajutit on vaja iga LED-iga profiili jaoks, kui soovitakse pidevat valgusjoont — ilma hajutita on LED-riba küll funktsionaalne, kuid valgus jääb tehniline. AST-35 ja RST-40 koos ASL40-ga annab ühtlase laia valgusjoone, mis sobib eriti suurte avalike ruumide jaoks.",

  "ASK100": "ASK100 on iseliimuv painduv LED-profiili valgusdifuusor (hajuti) — kompaktsem versioon meie hajuti-valikust, mõeldud MPV-301 ja MPV-302 mini-profiilide LED-kanali katmiseks. Iseliimuv tähendab, et hajuti kinnitatakse otse profiili sisse — ei vajata eraldi silikoontihendit ega libistamise meetodit. Polükarbonaatist (poolläbipaistev valge). Painduv: võimaldab paigaldust ka kõverustel. Hind on 1 m hajuti kohta, sisaldab 24% käibemaksu. NB! Hajutit on vaja iga LED-iga profiili jaoks, kui soovitakse pidevat valgusjoont. MPV-301 ja MPV-302 koos ASK100-ga annab peen valgusjoone põrandaliistu kõrval, mis sobib eriti hästi koridoride pehmeks öövalgustuseks. Tellitakse vastavalt LED-iga profiili kogusele.",

  "P1": "P1 on alumiinium-kinnitusvedru — TINLINE-seeria mini-põrandaliistu (MPA013, MPA302, MPA317, MVP018, MVP172, MPV301) kinnituseks. Erinevus klips-kinnitusest: vedru-süsteem annab tugevama ja müravaba kinnituse, võimaldab vajadusel liistu eemaldada ilma kahjustusteta. Paigaldatakse seina külge iga 50 cm tagant — liist ise kinnitub vedrude külge libistamisega. Müüakse tükihinnaga (0,50 € + KM = 0,61 € / tk). Sobib uutele ja renoveeritavatele põrandatele. Kogus vajamise järgi: 2 vedru iga jooksva meetri liistu kohta (alustada 5 cm seina nurgast). 2,6 m liistu kohta vaja 6 vedru; 10 m kohta 20 vedru. NB! Vedrud on TINLINE-seeria liistude kohustuslik tarvik — ilma nendeta liistu paigaldada ei saa. Tellitakse alati koos TINLINE-liistuga.",

  "F40": "F40 on alumiiniumist otsakomplekt ASP-40 põrandaliistule — sisaldab sisenurka, välisnurka, ühendust (kahe liistu otsade ühendamiseks), paremat ja vasakut otsapead (seina vastu lõpetamiseks). Kõigi nurkade ja otspeade lõpetamiseks vajalik — ilma otsakomplekti kasutamiseta jääb põrandaliistu otsad lahtisteks ja nurgad on raskemini lõpetatavad. Müüakse komplekti hinnaga (kõik 5 tükki koos). Sobib täpselt ASP-40 liistule (40 mm kõrgus). Värvuspalett ühildub liistuga — hõbe, valge, must; RAL-tellimusel sama toon kui liist (~5 nädalat). Materjal alumiinium — sama vastupidavus ja eluiga kui liistul. Hind on komplekti kohta, sisaldab 24% käibemaksu. NB! Otsakomplekt on igale ASP-seeria liistule eraldi (F40 → ASP-40, F60 → ASP-60, jne).",

  "F60": "F60 on alumiiniumist otsakomplekt ASP-60 põrandaliistule — sisaldab sisenurka, välisnurka, ühendust (kahe liistu otsade ühendamiseks), paremat ja vasakut otsapead (seina vastu lõpetamiseks). Kõigi nurkade ja otspeade lõpetamiseks vajalik — ilma otsakomplekti kasutamiseta jääb põrandaliistu otsad lahtisteks ja nurgad on raskemini lõpetatavad. Müüakse komplekti hinnaga (kõik 5 tükki koos). Sobib täpselt ASP-60 liistule (60 mm kõrgus). Värvuspalett ühildub liistuga — hõbe, valge, must; RAL-tellimusel sama toon kui liist (~5 nädalat). Materjal alumiinium — sama vastupidavus ja eluiga kui liistul. Hind on komplekti kohta, sisaldab 24% käibemaksu. NB! Otsakomplekt on igale ASP-seeria liistule eraldi (F40 → ASP-40, F60 → ASP-60, jne) ning ei ole vahetatav.",

  "F80": "F80 on alumiiniumist otsakomplekt ASP-80 põrandaliistule — sisaldab sisenurka, välisnurka, ühendust (kahe liistu otsade ühendamiseks), paremat ja vasakut otsapead (seina vastu lõpetamiseks). Kõigi nurkade ja otspeade lõpetamiseks vajalik — ilma otsakomplekti kasutamiseta jääb põrandaliistu otsad lahtisteks ja nurgad on raskemini lõpetatavad. Müüakse komplekti hinnaga (kõik 5 tükki koos). Sobib täpselt ASP-80 liistule (80 mm kõrgus). Värvuspalett ühildub liistuga — hõbe, valge, must; RAL-tellimusel sama toon kui liist (~5 nädalat). Materjal alumiinium — sama vastupidavus ja eluiga kui liistul. Hind on komplekti kohta, sisaldab 24% käibemaksu. NB! Otsakomplekt on igale ASP-seeria liistule eraldi (F40 → ASP-40, F60 → ASP-60, F80 → ASP-80, F100 → ASP-100).",

  "F100": "F100 on alumiiniumist otsakomplekt ASP-100 põrandaliistule — sisaldab sisenurka, välisnurka, ühendust (kahe liistu otsade ühendamiseks), paremat ja vasakut otsapead (seina vastu lõpetamiseks). Kõigi nurkade ja otspeade lõpetamiseks vajalik — ilma otsakomplekti kasutamiseta jääb põrandaliistu otsad lahtisteks ja nurgad on raskemini lõpetatavad. Müüakse komplekti hinnaga (kõik 5 tükki koos). Sobib täpselt ASP-100 liistule (100 mm kõrgus) — meie kõrgeim Arrow-seeria liist. Värvuspalett ühildub liistuga — hõbe, valge, must; RAL-tellimusel sama toon kui liist (~5 nädalat). Materjal alumiinium — sama vastupidavus ja eluiga kui liistul. Hind on komplekti kohta, sisaldab 24% käibemaksu. NB! Otsakomplekt on igale ASP-seeria liistule eraldi ning ei ole vahetatav teise seeria komplektiga."

};
