// Auto-generated index of product images. Maps SKU -> ordered image URLs.
window.__productImages = {
  "AST45": [
    "assets/products/AST45_1.avif",
    "assets/products/AST45_2.avif",
    "assets/products/AST45_3.avif",
    "assets/products/AST45_4.avif",
    "assets/products/AST45_5.avif",
    "assets/products/AST45_6.avif",
    "assets/products/AST45_7.avif",
  ],
  "MPA013": [
    "assets/products/MPA013.avif",
    "assets/products/MPA013_1.avif",
    "assets/products/MPA013_2.avif",
    "assets/products/MPA013_3.avif",
    "assets/products/MPA013_4.avif",
    "assets/products/MPA013_5.avif",
    "assets/products/MPA013_6.avif",
    "assets/products/MPA013_7.avif",
  ],
  "MPA301": [
    "assets/products/MPA301.avif",
    "assets/products/MPA301_1.avif",
    "assets/products/MPA301_2.avif",
    "assets/products/MPA301_3.avif",
    "assets/products/MPA301_4.avif",
    "assets/products/MPA301_5.avif",
    "assets/products/MPA301_6.avif",
    "assets/products/MPA301_7.avif",
    "assets/products/MPA301_8.avif",
    "assets/products/MPA301_9.avif",
    "assets/products/MPA301_10.avif",
  ],
  "MPA302": [
    "assets/products/MPA302_1.avif",
    "assets/products/MPA302_2.avif",
    "assets/products/MPA302_3.avif",
    "assets/products/MPA302_4.avif",
    "assets/products/MPA302_5.avif",
    "assets/products/MPA302_6.avif",
    "assets/products/MPA302_7.avif",
    "assets/products/MPA302_8.avif",
  ],
  "MVP018": [
    "assets/products/MVP018_1.avif",
    "assets/products/MVP018_2.avif",
    "assets/products/MVP018_3.avif",
    "assets/products/MVP018_4.avif",
  ],
  "MVP172": [
    "assets/products/MVP172.avif",
    "assets/products/MVP172_1.avif",
    "assets/products/MVP172_2.avif",
    "assets/products/MVP172_3.avif",
    "assets/products/MVP172_4.avif",
    "assets/products/MVP172_5.avif",
    "assets/products/MVP172_6.avif",
  ],
  "ASP100": [
    "assets/products/ASP100_4.jpg",
    "assets/products/ASP100_5.jpg",
    "assets/products/ASP100 hõbe.jpg",
    "assets/products/ASP100 must.jpg",
    "assets/products/ASP100 valge.jpg",
  ],
  "ASP102": [
    "assets/products/АSP102_Hall.jpg",
    "assets/products/АSP102_Must.jpg",
    "assets/products/АSP102_Valge.jpg",
  ],
  "ASP106": [
    "assets/products/ASP106_1.jpg",
    "assets/products/ASP106_2.jpg",
    "assets/products/ASP106_3.jpg",
    "assets/products/ASP106_hõbe_led.jpg",
  ],
  "ASP112": [
    "assets/products/ASP112_1.jpg",
    "assets/products/ASP112_2.jpg",
    "assets/products/ASP112_3.jpg",
  ],
  "ASP116": [
    "assets/products/ASP116_60mm_1.jpg",
    "assets/products/ASP116_60mm_2.jpg",
    "assets/products/ASP116_60mm_3.jpg",
    "assets/products/ASP116_60mm_4.jpg",
  ],
  "ASP116GK": [
    "assets/products/ASP116GK_60mm_1.jpg",
    "assets/products/ASP116GK_60mm_2.jpg",
    "assets/products/ASP116GK_60mm_3.jpg",
    "assets/products/ASP116GK_60mm_4.jpg",
  ],
  "ASP117": [
    "assets/products/ASP117_70mm_1.jpg",
    "assets/products/ASP117_70mm_2.jpg",
    "assets/products/ASP117_70mm_3.jpg",
  ],
  "ASP130": [
    "assets/products/ASP130_30mm_1.jpg",
    "assets/products/ASP130_30mm_2.jpg",
    "assets/products/ASP130_30mm_3.jpg",
  ],
  "ASP168": [
    "assets/products/ASP168_60mm_1.jpg",
    "assets/products/ASP168_60mm_2.jpg",
    "assets/products/ASP168_60mm_3.jpg",
  ],
  "ASP198": [
    "assets/products/ASP198.jpg",
  ],
  "ASP238": [
    "assets/products/ASP238_1.webp",
    "assets/products/ASP238_3.webp",
    "assets/products/ASP238_5.webp",
  ],
  "ASP36": [
    "assets/products/АSP36 valge.jpg",
  ],
  "ASP40": [
    "assets/products/ASP40  hõbe.jpg",
    "assets/products/ASP40 must.jpg",
    "assets/products/ASP40 valge.jpg",
    "assets/products/ASP40 hõbe ühendus.jpg",
    "assets/products/ASP40 must ühendus.jpg",
    "assets/products/ASP40  valge ühendus.jpg",
  ],
  "ASP60": [
    "assets/products/ASP60 hõbe.jpg",
    "assets/products/ASP60 must.jpg",
    "assets/products/ASP60 valge.jpg",
    "assets/products/ASP60 hõbe ühendus.jpg",
    "assets/products/ASP60 must ühendus .jpg",
    "assets/products/ASP60 ühendus.jpg",
  ],
  "ASP410": [
    "assets/products/ASP410_1.jpg",
    "assets/products/ASP410_2.jpg",
  ],
  "ASP411": [
    "assets/products/ASP411_1.jpg",
    "assets/products/ASP411_2.jpg",
  ],
  "ASP610": [
    "assets/products/ASP610_1.jpg",
    "assets/products/ASP610.jpg",
  ],
  "ASP611": [
    "assets/products/ASP611_1.jpg",
    "assets/products/ASP611_2.jpg",
  ],
  "ASP78": [
    "assets/products/ASP78_2_must.jpg",
    "assets/products/ASP78_2_valge.jpg",
  ],
  "ASP80": [
    "assets/products/ASP80 hõbe.jpg",
    "assets/products/ASP80 must.jpg",
    "assets/products/ASP80 valge.jpg",
  ],
  "ASP904": [
    "assets/products/ASP904_4.webp",
    "assets/products/ASP904_5.webp",
  ],
  "ASP905": [
    "assets/products/ASP905_3.webp",
    "assets/products/ASP905_5.webp",
  ],
  "ASPL100": [
    "assets/products/ASPL100_1.jpg",
    "assets/products/ASPL100_2.jpg",
    "assets/products/ASPL100_3.jpg",
    "assets/products/ASPL100_4.jpg",
  ],
  "ASPL130": [
    "assets/products/ASPL130_hõbe.jpg",
    "assets/products/ASPL130_must.jpg",
    "assets/products/ASPL130_valge.jpg",
  ],
  "ASPL35": [
    "assets/products/ASPL35_1.jpg",
    "assets/products/ASPL35_2.jpg",
    "assets/products/ASPL35_3.jpg",
    "assets/products/ASPL35_4.jpg",
    "assets/products/ASPL35_5.jpg",
  ],
  "ASPL60": [
    "assets/products/ASPL60_1.jpg",
    "assets/products/ASPL60_2.jpg",
    "assets/products/ASPL60_3.jpg",
    "assets/products/ASPL60_4.jpg",
    "assets/products/ASPL60_5.jpg",
  ],
  "AST10": [
    "assets/products/AST10_1.jpg",
    "assets/products/AST10_2.jpg",
    "assets/products/AST10_3.jpg",
  ],
  "AST12": [
    "assets/products/AST12_1.jpg",
    "assets/products/AST12_2.jpg",
    "assets/products/AST12_3.jpg",
  ],
  "AST14": [
    "assets/products/AST14_1.jpg",
    "assets/products/AST14_2.jpg",
    "assets/products/AST14_3.jpg",
    "assets/products/AST14_4.jpg",
    "assets/products/AST14_5.jpg",
    "assets/products/AST14_6.jpg",
    "assets/products/AST14_12.jpg",
  ],
  "AST14_12": [
    "assets/products/AST1412_1.jpg",
    "assets/products/AST1412_2.jpg",
    "assets/products/AST1412_3.jpg",
    "assets/products/AST1412_4.jpg",
    "assets/products/AST1412_5.jpg",
    "assets/products/AST1412_6.jpg",
  ],
  "ASP58": [
    "assets/products/ASP58_1 must.jpg",
    "assets/products/ASP58_1 valge.jpg",
    "assets/products/ASP58_2 hõbe.jpg",
    "assets/products/ASP58_2 must.jpg",
    "assets/products/ASP58_2 valge.jpg",
  ],
  "AST1412": [
    "assets/products/AST1412_1.jpg",
    "assets/products/AST1412_2.jpg",
    "assets/products/AST1412_3.jpg",
    "assets/products/AST1412_4.jpg",
    "assets/products/AST1412_5.jpg",
    "assets/products/AST1412_6.jpg",
  ],
  "AST149": [
    "assets/products/AST149_2.jpg",
    "assets/products/AST149_3.jpg",
    "assets/products/AST149_4.jpg",
    "assets/products/AST149_5.jpg",
    "assets/products/AST149_6.jpg",
  ],
  "AST20": [
    "assets/products/AST20_1.jpg",
    "assets/products/AST20_2.jpg",
    "assets/products/AST20_3.jpg",
  ],
  "AST201": [
    "assets/products/AST201_1.jpg",
    "assets/products/AST201_2.jpg",
    "assets/products/AST201_3.jpg",
    "assets/products/AST201_4.jpg",
    "assets/products/AST201_5.jpg",
    "assets/products/AST201_6.jpg",
  ],
  "AST22": [
    "assets/products/AST22_1.jpg",
    "assets/products/AST22_2.jpg",
    "assets/products/AST22_3.jpg",
  ],
  "AST30": [
    "assets/products/AST30_1.jpg",
    "assets/products/AST30_2.jpg",
    "assets/products/AST30_3.jpg",
    "assets/products/AST30_4.jpg",
    "assets/products/AST30_5.jpg",
    "assets/products/AST30_6.jpg",
  ],
  "AST35": [
    "assets/products/AST35_1.jpg",
    "assets/products/AST35_2.jpg",
    "assets/products/AST35_3.jpg",
    "assets/products/AST35_4.jpg",
    "assets/products/AST35_5.jpg",
    "assets/products/AST35_6.jpg",
  ],
  "AST5": [
    "assets/products/AST5_1.jpg",
    "assets/products/AST5_2.jpg",
    "assets/products/AST5_3.jpg",
  ],
  "AST50": [
    "assets/products/AST50_1.jpg",
    "assets/products/AST50_2.jpg",
    "assets/products/AST50_3.jpg",
  ],
  "AST8": [
    "assets/products/AST8_1.jpg",
    "assets/products/AST8_2.jpg",
    "assets/products/AST8_3.jpg",
  ],
  "LHV10": [
    "assets/products/LHV10_1.jpg",
    "assets/products/LHV10_2.jpg",
    "assets/products/LHV10_3.jpg",
    "assets/products/LHV10_4.jpg",
    "assets/products/LHV10_5.jpg",
    "assets/products/LHV10_6.jpg",
  ],
  "LPA909": [
    "assets/products/LPA909_1.webp",
    "assets/products/LPA909_2.webp",
    "assets/products/LPA909_3.webp",
  ],
  "MPA015": [
    "assets/products/MPA015_1 hõbe.jpg",
    "assets/products/MPA015_1 must.jpg",
    "assets/products/MPA015_1 valge.jpg",
    "assets/products/MPA015_2 hõbe.jpg",
    "assets/products/MPA015_2 must.jpg",
    "assets/products/MPA015_2 valge.jpg",
  ],
  "MPA217": [
    "assets/products/MPA217_1 hõbe.jpg",
    "assets/products/MPA217_1 must.jpg",
    "assets/products/MPA217_1 valge.jpg",
    "assets/products/MPA217_2 hõbe.jpg",
    "assets/products/MPA217_2 must.jpg",
    "assets/products/MPA217_2 valge.jpg",
  ],
  "RST1020": [
    "assets/products/RST1020_1.jpg",
    "assets/products/RST1020_2.jpg",
    "assets/products/RST1020.jpg",
  ],
  "RST1412": [
    "assets/products/RST1412_1.jpg",
    "assets/products/RST1412_2.jpg",
    "assets/products/RST1412_3.jpg",
    "assets/products/RST1412_4.jpg",
    "assets/products/RST1412_5.jpg",
    "assets/products/RST1412_6.jpg",
  ],
  "RST22": [
    "assets/products/RST22_1.jpg",
    "assets/products/RST22_2.jpg",
    "assets/products/RST22_3.jpg",
    "assets/products/RST22_4.jpg",
    "assets/products/RST22_5.jpg",
    "assets/products/RST22_6.jpg",
  ],
  "RST25": [
    "assets/products/RST25_1.jpg",
    "assets/products/RST25_2.jpg",
    "assets/products/RST25_3.jpg",
    "assets/products/RST25_4.jpg",
    "assets/products/RST25_5.jpg",
    "assets/products/RST25_6.jpg",
  ],
  "RST40": [
    "assets/products/RST40_1.jpg",
    "assets/products/RST40_2.jpg",
    "assets/products/RST40_3.jpg",
    "assets/products/RST40_4.jpg",
    "assets/products/RST40_5.jpg",
    "assets/products/RST40_6.jpg",
  ],
  "ASP40-NV":  ["assets/products/asp40-outer.png"],
  "ASP40-NS":  ["assets/products/asp40-inner.png"],
  "ASP40-OK":  ["assets/products/asp40-endcap.png"],
  "ASP40-Y":   ["assets/products/asp40-connector.png"],
  "ASP60-NV":  ["assets/products/asp60-outer.png"],
  "ASP60-NS":  ["assets/products/asp60-inner.png"],
  "ASP60-OK":  ["assets/products/asp60-endcap.png"],
  "ASP60-Y":   ["assets/products/asp60-connector.png"],
  "ASP80-NV":  ["assets/products/asp80-outer.png"],
  "ASP80-NS":  ["assets/products/asp80-inner.png"],
  "ASP80-OK":  ["assets/products/asp80-endcap.png"],
  "ASP80-Y":   ["assets/products/asp80-connector.png"],
  "ASP100-NV": ["assets/products/asp100-outer.png"],
  "ASP100-NS": ["assets/products/asp100-inner.png"],
  "ASP100-OK": ["assets/products/asp100-endcap.png"],
  "ASP100-Y":  ["assets/products/asp100-connector.png"],
  "HAJUTI-M":  ["assets/products/diffuser.png"],
};
